config/routes.rb
Railsrumble::Application.routes.draw do
  get "home/index"
  resources :tasks
  
  devise_for :users
  
  resources :users, :only => [:edit, :update]
  
  root :to => "home#index"
  get 'app' => 'home#app'
  get 'guest' => "home#sign_in_as_guest"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :tasks

  validates_presence_of :user, :name
end

app/models/concerns/task_type.rb
module TaskType
  extend ActiveSupport::Concern
  
  IMAGES = {
    homework: {
      keywords: ['assignment', 'report', 'homework'], 
      weight: 2.hours
    },
    cart: {
      keywords: ['buy', 'shop', 'grocery'],
      weight: 1.hour
    },
    book: {
      keywords: ['read', 'study', 'exam'],
      weight: 2.hours
    },
    phone: {
      keywords: ['call, phone'],
      weight: 10.minutes
    },
    email: {
      keywords: ['email'],
      weight: 5.minutes
    },
    people: {
      keywords: ['meet', 'people'],
      weight: 30.minutes
    },
    food: {
      keywords: ['cook', 'food', 'eat'],
      weight: 40.minutes
    },
    mop: {
      keywords: ['clean'],
      weight: 1.hour
    },
    tools: {
      keywords: ['fix', 'repair'],
      weight: 1.hour
    },
    heart: {
      keywords: ['date', 'love', 'flower', 'heart'],
      weight: 4.hours
    },
    zoom: {
      keywords: ['find', 'search'],
      weight: 20.minutes
    },
    run: {
      keywords: ['exercise', 'workout', 'gym'],
      weight: 30.minutes 
    },
    game: {
      keywords: ['play', 'game'],
      weight: 1.hour
    },
    sleep: {
      keywords: ['sleep', 'rest'],
      weight: 8.hours 
    },
    write: {
      keywords: ['write', 'blog'],
      weight: 2.hours
    },
    airplane: {
      keywords: ['travel', 'flight'],
      weight: 4.hours
    },
    cup: {
      keywords: ['drink'],
      weight: 5.minutes
    },
    print: {
      keywords: ['print'],
      weight: 1.minute
    },
    twitter: {
      keywords: ['facebook', 'twitter'],
      weight: 1.minute
    },
    laundry: {
      keywords: ['laundry'],
      weight: 2.hours
    },
    code: {
      keywords: ['code', 'program'],
      weight: 2.hours
    },
    none: {
      keywords: [],
      weight: 0
    }
  }
  
  def find_image(description)
    words = description.split(/[\s.,;\/\\\\]/)
    keywords = IMAGES.map{|k,v| v[:keywords]}.flatten
    matches = []
    keywords.each do |keyword|
      if description.index(keyword) != nil
        matches = matches + [keyword]
      end
    end
    image_lookup(matches)
  end
  
  def image_lookup(keyword)
    matches = []
    IMAGES.each do |image, keywords|
      matches << image.to_s unless (keywords[:keywords] & keyword).empty?
    end
    matches << "none" if matches.empty?
    matches = matches[1..4] if matches.length > 4
    return matches
  end
  
  def update_task_type
    self.task_type = find_image(self.description)
    self.weight = IMAGES[self.task_type.first.to_sym][:weight]
  end

  included do
    before_save :update_task_type
  end
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  include TaskType
  
  belongs_to :user
  belongs_to :category
  serialize :task_type

  validates_presence_of :user, :description
  
  before_save :truncate_description

  def mark_completed
  	self.completed = true
  	save
  end
  
  def truncate_description
    self.description = truncate(self.description, :length => 60)
  end
  
  def category_name
    if self.category
      return self.category.name
    else
      return ""
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :categories, :dependent => :destroy
  has_many :tasks, :through => :categories, :dependent => :destroy

  validates :email, :presence => true

  def tasks(params={})
    conditions = {:user => self}
    conditions[:category] = params[:category] if params[:category]
    conditions[:task_type] = params[:task_type] if params[:task_type]
    conditions[:priority] = params[:priority] if params[:priority]

    return Task.where(conditions)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_filter :authenticate_user!
  def index
    redirect_to action: 'app' if user_signed_in?
  end
  
  def app
    redirect_to root_path if not user_signed_in?
  end
  
  def sign_in_as_guest
    guest = User.find_or_create_by_name(name: "Guest", password: "guest123", email:"email@guest.com")
    sign_in guest
    redirect_to action: 'app'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    params = task_params.merge({:user => current_user})
    @task = Task.new(params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params

      params.require(:task).permit(:description, :task_type, :priority, :time, :user, :category, :id, :completed)

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to controller: 'home', action: 'app', notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/app.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>
<style type="text/css">
body{

    background-image: url("/images/retina_wood.png");
}
</style>
<div class = "container" id = "differentBG">

    <div ng-app="toDoApp">
        <section ng-controller="TodoController">

            <form  role="search" class="navbar-form" ng-submit="createTodo()">

                <input  class="form-control todoInput" placeholder="New Task" ng-model="newTodo" autofocus maxlength="60" />
            </form>
            <button type="button" ng-disabled="allCompleted" ng-click="completeAll()" class="btn btn-default mark">Mark all as complete</button>

            <section ng-show="todos.length" ng-cloak>

                <ul ui-sortable class= "sticky">
                    <li ng-repeat="todo in todos" ng-class="{done:isCompleted(todo)}">
                        <span class="checkIcon glyphicon glyphicon-ok-circle" ng-click="complete(todo)" ng-class="{incomplete:isPending(todo)}"></span>
                        <span class="deleteIcon glyphicon glyphicon-remove-circle" ng-click="delete(todo)" ng-class="{incomplete:isPending(todo)}"></span>
                        <h2 ng-dblclick="editTodo(todo)">{{todo.description}}</h2>
                        
                        <div class = "imgHolder">
                            <img ng-repeat="type in todo.task_type" src="/images/types/{{type}}.png">
                        </div>
                    </li></ul>



                </section>
                <footer id="footer" ng-show="todos.length" ng-cloak>
                    <span id="todo-count"><strong>{{pendingCount}}</strong>
                        <ng-pluralize count="pendingCount" when="{ one: 'item left', other: 'items pending' }"></ng-pluralize>
                    </span>


                </footer>
            </section>
        </div>
        
    </div>
    <script src="js/vendor/angular-resource.js"></script>
    <script src="js/main.js"></script>
    <script src="js/controllers/toDoController.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script type="text/javascript" src="js/directives/sortable.js"></script>

app/views/home/index.html.erb
<div class = 'container'>
	<div class = 'jumbotron'>
		<h1>SwiftTasks</h1>
    Become more productive by using our sticky note todo app that helps you plan your tasks better. 
    The app can recognize the type of task to predict how much you can do in a day in future.
    <br/>
		<a class="btn btn-primary" href="/guest">Get Started</a>
</div>

 <script type="text/javascript">
   var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
   rumbleBannerBackgroundColor = "#161616";
   rumbleBannerTextColor = "#b0b0b0";
   rumbleBannerLinkColor = "#ffffff";
   rumbleBannerPlacement = "bottom";
 </script>
 <script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><%= image_tag "/images/logo.png", :size=> "32x32"%><span>SwiftTasks</span></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if not user_signed_in? %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwiftTasks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap -->
  <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
  <link href="/css/overrides.css" rel="stylesheet" media="screen">
  <link href="/css/ours.css" rel="stylesheet" media="screen">
  <link  href="http://fonts.googleapis.com/css?family=Reenie+Beanie:regular" rel="stylesheet" type="text/css"> 
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
</head>
<body>
  <%= render 'layouts/nav_bar' %>

    <% if notice  %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>   

  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="/js/vendor/bootstrap.min.js"></script>
  <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
  <script>
  (function (b, o, i, l, e, r)
  {
    b.GoogleAnalyticsObject = l; b[l] || (b[l] =
      function () { (b[l].q = b[l].q || []).push(arguments) }); b[l].l = +new Date;
    e = o.createElement(i); r = o.getElementsByTagName(i)[0];
    e.src = '//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e, r)
  }(window, document, 'script', 'ga'));
  ga('create', 'UA-XXXXX-X'); ga('send', 'pageview');
  </script>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, :html=>{"role"=>"form"}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation"  class="alert alert-dismissable alert-danger">
       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul >
      <% @task.errors.full_messages.each do |msg| %>
        <li  ><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.label :task_type %><br>
    <%= f.text_field :task_type %>
  </div>
  <div class="form-group">
    <%= f.label :priority %><br>
    <%= f.number_field :priority, "min"=>"1","max"=>"10" %>
  </div>
  <div class="form-group">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="form-group">
    <%= f.submit :class=>"btn btn-default"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Type</th>
      <th>Priority</th>
      <th>Time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.task_type %></td>
        <td><%= task.priority %></td>
        <td><%= task.time %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @task.task_type %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Time:</strong>
  <%= @task.time %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit 'save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>